---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    consul:
      config:
        datacenter: dc1
        encrypt: Dt3P9SpKGAR/DIUN1cDirg==

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    require_chef_omnibus: 12.5.1
    run_list:
      - recipe[consul-ng::default]
    attributes:
      consul:
        config:
          bootstrap: true
          server: true
